const errorTypes = () => ({
  AUTH_EMAIL_ALREDY_EXISTS: "AUTH_EMAIL_ALREDY_EXISTS",
  AUTH_INVALTD_TOKEN: "AUTH_INVALTD_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_WRONG_PASSWORD: "AUTH_WRONG_PASSWORD",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUHORIZED_ACCESS: "AUTH_UNAUHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",

  // ACCESS CONTROL ERRORS
  ACCESS_FORBIDDEN: "ACCESS_FORBIDDEN",
  ACESS_UNAUTHORIZED: "ACESS_UNAUTHORIZED",

  // VALIDATION AND RESOURCE ERRORS
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // SYSTEM ERRORS
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR: "VERIFICATION_ERROR",

  BAD_REQUEST: "BAD_REQUEST",

  UNAUTHORIZED: "UNAUTHORIZED",
});

export const ErrorType = errorTypes();


export type ErrorTypeSignature = keyof typeof ErrorType